import Layout from "../components/Layout";
import SobreMi from "../components/SobreMi";
import Head from "next/head";

export default function About() {
  return (
    <div>
      <Head>
        <title>Sobre mi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <SobreMi />
      </Layout>
    </div>
  );
}
