import Layout from "../components/Layout";
import Contactame from "../components/Contactame";
import Head from "next/head";

export default function Contact() {
  return (
    <div>
      <Head>
        <title>Contáctame</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Contactame />
      </Layout>
    </div>
  );
}
