import Head from 'next/head'
import Bienvenida from '../components/Bienvenida'
import Layout from '../components/Layout'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Bienvenid@</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logopc.png" />
      </Head>

      <Layout>
        <Bienvenida/>
      </Layout>
    </div>
  )
}
