import Layout from "../components/Layout";
import Proyectos from "@components/Proyectos";
import Head from "next/head";
import fs from 'node:fs/promises'
import projectsFile from '@content/projects.json'

export default function Projects() {
  return (
    <div>
      <Head>
        <title>Proyectos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logopc.png" />
      </Head>
      <Layout>
        <Proyectos />
      </Layout>
    </div>
  );
}

export async function getStaticProps() {
  const projects = await fs.readFile(projectsFile)

  console.log(projects)

  return {
    props: {
      projects: []
    }
  }
}
