import Layout from "../components/Layout";
import Proyectos from "../components/Proyectos";
import Head from "next/head";

export default function Projects() {
  return (
    <div>
      <Head>
        <title>Proyectos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Proyectos />
      </Layout>
    </div>
  );
}
