import Layout from "../components/Layout";
import Proyectos from "@components/Proyectos";
import Head from "next/head";
import fs from 'node:fs/promises'
import path from 'node:path'
import process from 'node:process'

export default function Projects({ projects }) {
  return (
    <div>
      <Head>
        <title>Proyectos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logopc.png" />
      </Head>
      <Layout>
        <Proyectos data={projects} />
      </Layout>
    </div>
  );
}

export async function getStaticProps() {
  const projects = await fs.readFile(path.join(process.cwd(), 'src', 'content','projects.json')).then(JSON.parse)

  return {
    props: {
      projects
    }
  }
}
